- src/Aqua.jl
- src/ambiguities.jl
- src/utils.jl
This is for avoiding errors like
> ```
> ERROR: MethodError: no method matching detect_ambiguities(::Module, ::Module; recursive=true, imported=false, ambiguous_bottom=false)
> Closest candidates are:
>   detect_ambiguities(::Any...; recursive, ambiguous_bottom) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1423 got unsupported keyword argument "imported"
> ```
>
> --- https://travis-ci.com/github/JuliaFolds/BangBang.jl/jobs/381666899#L338
Also:
https://github.com/JuliaFolds/Transducers.jl/runs/1077261987#step:6:37
Workaround over-sensitive ambiguity detection from JuliaLang/julia#36962 (#32)
* Do not hard-code default options for `Test.detect_ambiguities`
* Ignore ambiguities from Base for now
> Workaround over-sensitive ambiguity detection from JuliaLang/julia#36962

- README.md
- src/Aqua.jl
- src/deps_compat.jl
- src/utils.jl
- test/test_deps_compat.jl
- test/test_smoke.jl
close #31
Add test_deps_compat to check missing compat in root Project.toml (#33)
A new function `test_deps_compat` runs a test to check if
`Project.toml` has enough `compat` entries.
> Add test_deps_compat to check missing compat in root Project.toml

- src/Aqua.jl
- src/utils.jl
- test/test_smoke.jl
- test/test_utils.jl
Make test_all configurable with flags (#35)
There are a lot of repetition across packages for running optional
tests.  Let's avoid this by including all tests in `test_all` and
turning on/off by flags.
> Make test_all configurable with flags

- src/deps_compat.jl
- test/test_deps_compat.jl
https://travis-ci.com/github/JuliaFolds/InitialValues.jl/jobs/382136912#L291-L295
Fix test_deps_compat for Project.toml without deps table (#38)
To run `test_deps_compat` by default in Aqua 0.5 (#36), it should work
Project.toml file without `deps`.
> Fix test_deps_compat for Project.toml without deps table

- .github/workflows/test.yml
- README.md
- src/project_toml_formatting.jl
- src/utils.jl
- test/test_project_toml_formatting.jl
Make it work on Windows (#43)
* Run tests on Windows.
* Ignore carriage returns.
It looks like running tests on Windows didn't catch the carriage
return bug.  But it might be worth running tests on Windows anyway to
catch some similar bugs in the future.
> Make it work on Windows

- src/ambiguities.jl
Ref: https://github.com/JuliaTesting/Aqua.jl/pull/71/files#r834842406.  If you have better ideas about how to more proper fix this or how to actually test this code path which is clearly untested, please take over this PR or open a new one, but at least this doesn't break the package in older versions of Julia.  Not very useful to have a QUality Assurance package that breaks your tests.
CC:  @Roger-luo
> Fix `UndefVarError` in Julia v1.0-1.3

- src/exports.jl
`getproperty` triggers deprecation warnings: avoid triggering those when walking modules.
Fix https://github.com/JuliaTesting/Aqua.jl/issues/83.
Also observed in the `UnicodePlots` [test suite](https://github.com/JuliaPlots/UnicodePlots.jl/actions/runs/3465118212/jobs/5787474874#step:6:337), unfortunately this PR only fixes `GeometryBasics` tests mentioned in the issue, we also need a PR in `Reexports.jl` or `Colors.jl`.
> do not trigger deprecation warnings

- src/utils.jl
> Fix project order for 1.9

- src/project_toml_formatting.jl
Currently, only `Project.toml` and `test/Project.toml` are checked for their formatting. This PR adds the same check for `docs/Project.toml`, if that file exists.
Resolves #51.
> Check `docs/Project.toml` as well, if it exists

- src/stale_deps.jl
Otherwise, if any of the loaded packages prints during loading, this messes up things.
Real-world example: GAP.jl, where there is a `\r` being printed by some C code it loads; we'll try to fix that there, but it seems prudent to add this bit of defensive coding regardless of that.
Resolves #60
> Make analyze_stale_deps more robust

- docs/src/index.md
- src/piracy.jl
This PR fixes https://github.com/JuliaTesting/Aqua.jl/issues/94.
> Add `Aqua.Piracy` to autodocs block

- src/unbound_args.jl
Explain how seemingly well define typevars can result in unbound args in the presence of Vararg, and also display the offending methods in a more readable way.
Closes #87
> Improve error message on unbound args

- .github/workflows/docs.yml
- docs/make.jl
- src/Aqua.jl
This is an experiment, not sure if it will work.
> CI: switch docs CI to standard setup

- src/Aqua.jl
- src/ambiguities.jl
- src/exports.jl
- src/piracy.jl
- src/stale_deps.jl
- src/unbound_args.jl
Resolves https://github.com/JuliaTesting/Aqua.jl/issues/109.
This adds a `broken` kwarg (default `false`) to the tests `ambiguities`, `exports`, `piracy`, and `unbound_args`.
For the other tests it a lot harder to do as the tests are executed in a loop, and, after thinking some more about it, a lot less sensible after all.
> Add kwarg `broken`

- README.md
At least I have no intention to maintain them; they only differ by
defaults, so anyone using Aqua can easily adapt to them if desired. In
contrast it requires additional effort to maintain three release series,
with unclear benefits.
> Drop claims that 0.4 and 0.5 are still maintained

- src/piracy.jl
- test/test_piracy.jl
If the type of a method *argument* is a union, then if *any* of the types in the union is foreign, the whole type should count as foreign.
But when installing a method for a union, then it should only count as foreign if *all* the types in the union are foreign.
Resolves #114
> Fix some incorrect piracy flagging

- src/Aqua.jl
The only difference are the default values for certain keyword
arguments. Anyone using Aqua can easily pass different values
for these without the need of additional Aqua versions.
> Remove support for 0.4.x & 0.5.x series

- src/ambiguities.jl
- src/piracy.jl
- test/pkgs/PkgWithAmbiguities.jl
- test/test_ambiguities.jl
Fixes https://github.com/JuliaTesting/Aqua.jl/issues/49 and fixes https://github.com/JuliaTesting/Aqua.jl/issues/141.
The main change is the unwrapping of `UnionAll`s in `getobj`. While looking through it, I furthermore used it in the piracy tests as well (where until now the function was basically inlined). And in `getobj` the deprecated function `tuple_type_head` was used, the alternative is `fieldtype(-, 1)`. Both changes have been tested in julia 1.0, 1.6 and 1.9.
The MWE in https://github.com/JuliaTesting/Aqua.jl/issues/49#issue-711726567 by @mtsch for julia 1.0 (`Aqua.test_ambiguities([MWE, Base, Core], exclude=[convert])`) reports precisely the same 52 ambiguities (up to order) as with the current master, but there are no errors. 
The much smaller MWE in …
> Fix `getobj` for parameterized callable objects

- src/Aqua.jl
This now reflects the order the tests are actually run in.
> Update test order in main docstring

- src/piracy.jl
Followup to #131 (mentioned in https://github.com/JuliaTesting/Aqua.jl/pull/131#discussion_r1237021083).
The first parameter (the function type) is already checked prior. So currently, it is checked twice, which is not needed and may be confusing in the future when changing the semantics of `is_foreign_method` and `is_foreign`.
> Make piracy tests slightly more efficient

- docs/make.jl
- docs/src/internals.md
Accessible via https://juliatesting.github.io/Aqua.jl/dev/internals/
It contains no sensible content, so I don't know why we should keep it.
> Remove hidden doc page

- src/Aqua.jl
- src/piracy.jl
This implicitly fixes some wrong references in docstrings (`test_piracy` instead of `Piracy.test_piracy`) and sorts `test_piracy` alphabetically between the other docstrings.
Furthermore works around https://github.com/JuliaLang/julia/issues/36529 by making it obsolete, i.e. tab-completing `Aqua.test_piracy` in the REPL works now.
> Move `test_pirate` out of the `Aqua.Piracy` module

- src/piracy.jl
- test/pkgs/PiracyForeignProject/Project.toml
- test/pkgs/PiracyForeignProject/src/PiracyForeignProject.jl
- test/test_piracy.jl
Resolves https://github.com/JuliaTesting/Aqua.jl/issues/138, resolves https://github.com/JuliaTesting/Aqua.jl/issues/96.
> Piracy: Add kwarg `treat_as_own`

- src/ambiguities.jl
- test/test_ambiguities.jl
Changes:
- Formatting, it annoys me every time I want to change something that I cannot run the autoformatter
- Parse the output of `test_ambiguities_impl` to allow better testing (number of ambiguities and errors inside `getobj`)
- Adapt the tests
> Refactor `ambiguities.jl`

- src/Aqua.jl
- src/piracy.jl
This branch contains some special code for versions between https://github.com/JuliaLang/julia/pull/36962 (`v1.6.0-DEV.816`) and https://github.com/JuliaLang/julia/pull/37484 (`v1.6.0-DEV.875`).
I think Aqua should not need to support DEV builds that are more than 2 years old.
Thus I propose to remove the branch.
> Remove special branch for some julia v1.6.0-DEV versions

- Project.toml
- src/ambiguities.jl
- test/pkgs/PkgWithAmbiguities.jl
- test/test_ambiguities.jl
As written in the removed comment, `test_ambiguities` does not allow non-singleton callable in `exclude`. This is working now.
I furthermore changed the behavior for singleton callables to be the same. And I introduced constructors for `exclude`.
Unfortunately, one can only exclude the constructor of type `MyType` and all callables of `MyType` simultaneously, or none of both.
For my convenience, this already includes the changes of https://github.com/JuliaTesting/Aqua.jl/pull/143.
This change is probably breaking, semi-documented behavior of `exclude` for `test_ambiguities`. I thus bumped the version.
> Enhance `test_ambiguities`

- src/piracy.jl
Due to a dumb typo on my side (which I definitely should have noticed), the `test_piracy` kwarg `treat_as_own` is broken in the `0.6.4` release. This fixes it. I propose the following line of action:
Is this fine for you @fingolfin ?
> Fix `treat_as_own`

- src/piracy.jl
- test/pkgs/PiracyForeignProject/src/PiracyForeignProject.jl
- test/test_piracy.jl
Resolves https://github.com/JuliaTesting/Aqua.jl/issues/155 and resolves https://github.com/JuliaTesting/Aqua.jl/issues/157.
The main change is a re-implementation of `all_methods`. Unfortunately, the old data source `names(MyModule)` was missing some callables (https://github.com/JuliaTesting/Aqua.jl/issues/157) and methods of non-imported functions that have been defined in a fully qualified way (https://github.com/JuliaTesting/Aqua.jl/issues/155). The proposed implementation works very similarly to `Test.detect_ambiguities` and `Test.detect_unbound_args` by iterating over all `names` of all currently loaded modules, and then filtering out the methods that are indeed defined in `MyModule`.
I furthermore added some tests displaying the new functionality. The main point here is that …
> Enhance Piracy detection by considering more methods

- src/ambiguities.jl
Resolves https://github.com/JuliaTesting/Aqua.jl/issues/165.
@fingolfin please check that on your machine as well.
This should be backported to 0.6.6 and released, as it should occur for every package with many (>150 ambiguities).
> Circumvent pipe buffer deadlock

- src/ambiguities.jl
The do-block form ensures that the files are automatically closed
> Do-block in `mktemp` in `_find_ambiguities`

- Project.toml
- src/piracy.jl
Fixes https://github.com/JuliaTesting/Aqua.jl/issues/167.
This is only an issue on the `release-0.6` branch, as this change has been included in #156.
@fingolfin Could you tag this as 0.6.7?
> Protect access to `.instance`

- .github/workflows/docs.yml
- .github/workflows/test.yml
Otherwise hanging tests block a CI runner for up to 6 hours
> CI: set a timeout of 10 minutes

- .github/workflows/docs.yml
This is recommended by the [readme](https://github.com/julia-actions/setup-julia#inputs).
> CI: use concrete action version

- docs/Project.toml
I know that there already is a `1.0.1`, but since there are some issues with the docs (cf. #181), I would like to first fix it for the previous Documenter version (and thus fix its version), and then at a later point bump it to 1.0.
> Add compat for `Documenter.jl`

- src/exports.jl
- test/test_undefined_exports.jl
Resolves https://github.com/JuliaTesting/Aqua.jl/issues/176.
I would not consider this a breaking change, as it only changes the internal function `undefined_exports`, but the semantics of `test_undefined_exports` stay identical.
> Print module in `test_undefined_exports` report

- src/Aqua.jl
- src/pkg/Versions.jl
The version numbers have been found using the approach in https://github.com/JuliaLang/Compat.jl/tree/release-3#developer-tips.
> Streamline uses of Compat.jl

- .github/workflows/docs.yml
- .github/workflows/test.yml
to be able to run the documentation build for all skipped versions (cf. #182)
> Make CI jobs runable by hand

- CHANGELOG.md
- src/utils.jl
Fixes https://github.com/JuliaTesting/Aqua.jl/issues/186.
`is_kwcall` currently fails on julia 1.8 and older for methods where the third argument type is not a `DataType` but e.g. a `TypeVar`. This change only calls the erroring function in case that it is indeed a `DataType`.
> Fix `is_kwcall` for methods with type parameters

- .github/workflows/test.yml
Test on macos as well, as well as against julia nightly on both macos and windows to hopefully catch problems early.
> Add more CI targets

- CHANGELOG.md
- src/stale_deps.jl
Closes https://github.com/JuliaTesting/Aqua.jl/issues/136 as proposed in https://github.com/JuliaTesting/Aqua.jl/issues/136#issuecomment-1738637286.
> Add package extensions to `test_stale_deps` docstring

- .github/workflows/enforce-labels.yml
Basically a copy of https://github.com/JuliaLang/julia/pull/48359. I think this is worth to try.
> Add CI job checking for bad PR labels

- CHANGELOG.md
- src/deps_compat.jl
- test/test_smoke.jl
Resolves https://github.com/JuliaTesting/Aqua.jl/issues/178 and adds the same for `weakdeps` as well.
The tests are disabled by default, until maybe the next breaking release (see https://github.com/JuliaTesting/Aqua.jl/pull/202).
> Add option to `test_deps_compat` to test extras and weakdeps

- CHANGELOG.md
- src/deps_compat.jl
- test/test_smoke.jl
This should only be merged once a breaking release is staged. 
As this builds upon https://github.com/JuliaTesting/Aqua.jl/pull/200, that one has to be merged first.
> Change defaults for `check_extras` and `check_weakdeps`

- CHANGELOG.md
- src/deps_compat.jl
- src/utils.jl
- test/test_deps_compat.jl
- test/test_smoke.jl
Resolves https://github.com/JuliaTesting/Aqua.jl/issues/212.
> Remove special handling of stdlibs in `test_deps_compat`

- CHANGELOG.md
- docs/src/index.md
- src/Aqua.jl
- src/persistent_tasks.jl
- test/pkgs/PersistentTasks/PersistentTask/Project.toml
- test/pkgs/PersistentTasks/PersistentTask/src/PersistentTask.jl
- test/pkgs/PersistentTasks/TransientTask/Project.toml
- test/pkgs/PersistentTasks/TransientTask/src/TransientTask.jl
- test/pkgs/PersistentTasks/UsesBoth/Project.toml
- test/pkgs/PersistentTasks/UsesBoth/src/UsesBoth.jl
- test/test_persistent_tasks.jl
- test/test_smoke.jl
This checks whether a package spawns persistent `Task`s that might block precompilation of dependents of the package. It also provides a convenience utility, `test_persistent_tasks_deps`, for checking all the dependencies of a given package, to simplify discovery. If one runs one of the tests in this PR without annotating one as an expected failure, here is the output on Julia 1.10-beta:
```julia
julia> Aqua.test_persistent_tasks_deps(getid("UsesBoth"))
Generating  project jl_jqh8hMTOr6:
/tmp/jl_jqh8hMTOr6/Project.toml
/tmp/jl_jqh8hMTOr6/src/jl_jqh8hMTOr6.jl
Activating project at `/tmp/jl_jqh8hMTOr6`
Resolving package versions...
Updating `/tmp/jl_jqh8hMTOr6/Project.toml`
[94ae9332] + TransientTask v0.1.0 `~/.julia/dev/Aqua/test/pkgs/PersistentTasks/TransientTask`
Updating …
```
> Add persistent_tasks test

- CHANGELOG.md
- src/ambiguities.jl
- test/pkgs/PkgWithAmbiguities.jl
- test/test_ambiguities.jl
Resolves https://github.com/JuliaTesting/Aqua.jl/issues/79.
After this change, excluding some `foo` additionally excludes all instances of `Core.kwfunc(foo)` that belong to `foo` (i.e. the third parameter of the signature is `typeof(foo)`.
> Enhance `test_ambiguities`' exclude options for functions with kwargs

- CHANGELOG.md
- src/ambiguities.jl
- src/piracies.jl
Resolves #226.
Sorts both the reported ambiguities and type piracies by function name for easier fixing.
> Sort ambiguities and type piracies by function name

- CHANGELOG.md
- src/project_extras.jl
- test/test_project_extras.jl
It is very easy to miss that this error only occurs because of a
missing compat entry for Julia...
> Improve error when [extras] and test/Project.toml inconsistent

- CHANGELOG.md
- src/deps_compat.jl
- test/test_deps_compat.jl
Resolves https://github.com/JuliaTesting/Aqua.jl/issues/235.
As this is point 7 in the [guidelines for the General registry](https://juliaregistries.github.io/RegistryCI.jl/stable/guidelines/#New-packages), I support Aqua checking this.
> Require `[compat]` entry for `julia`

- CHANGELOG.md
- Project.toml
- README.md
- docs/src/index.md
This makes all necessary changes after a merge of https://github.com/JuliaTesting/Aqua.jl/pull/236 to release version 0.8.0.
> Release version 0.8.0

- docs/src/index.md
- src/persistent_tasks.jl
Also adds a cross-ref from `test_persistent_tasks`.
CC @NHDaly
> Add `find_persistent_task_deps` to doc build

- .github/workflows/test.yml
Some jobs occasionally fail due to a timeout. A small increase could help with that.
> Increase CI timeout

- src/Aqua.jl
- src/ambiguities.jl
- src/deps_compat.jl
- src/persistent_tasks.jl
- src/project_extras.jl
- src/stale_deps.jl
- src/utils.jl
- test/pkgs/AquaTesting.jl
- test/pkgs/sample/PkgWithCompatibleTestProject/Project.toml
- test/pkgs/sample/PkgWithIncompatibleTestProject/Project.toml
- test/pkgs/sample/PkgWithoutDeps/Project.toml
- test/pkgs/sample/PkgWithoutDeps/src/PkgWithoutDeps.jl
- test/pkgs/sample/PkgWithoutProject/src/PkgWithoutProject.jl
- test/test_project_extras.jl
- test/test_stale_deps.jl
This is a first step towards https://github.com/JuliaTesting/Aqua.jl/issues/180 as it gets rid of `LazyTestResult`, which is inherently incompatible with returning a list of things. Furthermore, it makes the code more readable without it.
And some more minor cleanup.
> Refactor `LazyTestResult` away

- CHANGELOG.md
- Project.toml
- src/persistent_tasks.jl
By using `io=devnull` option, which is only available in Julia 1.9 and above.
> persistent_tasks: suppress logs from Pkg.jl

- CHANGELOG.md
- docs/make.jl
- docs/src/ambiguities.md
- docs/src/deps_compat.md
- docs/src/exports.md
- docs/src/index.md
- docs/src/persistent_tasks.md
- docs/src/piracies.md
- docs/src/project_extras.md
- docs/src/stale_deps.md
- docs/src/test_all.md
- docs/src/unbound_args.md
- src/Aqua.jl
- src/ambiguities.jl
- src/exports.jl
- src/persistent_tasks.jl
- src/piracies.jl
- src/unbound_args.jl
Structurize, fill with content etc.:
Preview at https://juliatesting.github.io/Aqua.jl/previews/PR250/
> Overhaul documentation

- src/stale_deps.jl
I just got this error
```
Stale dependencies: Test Failed at /home/x/.julia/packages/Aqua/9p8ck/src/stale_deps.jl:31
Expression: isempty(stale_deps)
Evaluated: isempty(Base.PkgId[Base.PkgId(Base.UUID("9e88b42a-f829-5b0c-bbe9-9e923198166b"), "Serialization")])
```
So I think this bug is fixed.
Would tests be expected for this PR?
> Update stale deps stdlibs known bug warning

- CHANGELOG.md
- src/project_extras.jl
- test/test_project_extras.jl
Julia changed the printing in https://github.com/JuliaLang/julia/pull/52795 which then made our tests fail as we check against a concrete string.
Resolves https://github.com/JuliaTesting/Aqua.jl/issues/274.
> Use custom printing of UUIDs instead of relying on Base

- CHANGELOG.md
- src/ambiguities.jl
- src/exports.jl
- src/piracies.jl
- src/unbound_args.jl
Resolves https://github.com/JuliaTesting/Aqua.jl/issues/231.
The tests that may print long lists of things now only do that in the case of a failure. If the test is supplied `broken=true`, only the number of instances is printed instead.
> Make broken tests less noisy

- docs/Project.toml
- docs/src/persistent_tasks.md
There was a missing closing parenthesis, and `Aqua` was not being imported in the block. This PR fixes these.
> Fix failing persistent task example in doc

- CHANGELOG.md
- src/persistent_tasks.jl
- test/pkgs/PersistentTasks/PrecompilableErrorPkg/Project.toml
- test/pkgs/PersistentTasks/PrecompilableErrorPkg/src/PrecompilableErrorPkg.jl
- test/test_persistent_tasks.jl
I often experience precompilable errors in development when sorting out type piracy etc., e.g. when moving functions to a dependency and thus creating method overwriting. This change let's the persistent task test succeed in the case of a precompilable error to smooth these cases, with the possibility to opt-in into getting this as a failure instead.
> Add kwarg `succeed_on_precompilable_error`

- CHANGELOG.md
- src/persistent_tasks.jl
- test/pkgs/PersistentTasks/PrecompilableErrorPkg/Project.toml
- test/pkgs/PersistentTasks/PrecompilableErrorPkg/src/PrecompilableErrorPkg.jl
- test/test_persistent_tasks.jl
Reverts JuliaTesting/Aqua.jl#285.
Resolves #287.
> Revert "Add kwarg `succeed_on_precompilable_error`"

- CHANGELOG.md
- Project.toml
- docs/src/persistent_tasks.md
While helping someone on slack I noticed these docs were a bit less clear than they could be. Here's my attempt at improving them. CC @NHDaly.
> Expand and clarify docs on persistent tasks

- CHANGELOG.md
- Project.toml
- src/Aqua.jl
Reporting ambiguities that cannot be fixed by the user since they are not part of the testtarget can be harmful to the user experience since they will never be useful, since at least JuliaLang/julia#36962.
Fixes #77
> remove Base and Core from ambiguities test

- src/Aqua.jl
same as https://github.com/JuliaTesting/Aqua.jl/pull/319 but for the newly added test from https://github.com/JuliaTesting/Aqua.jl/pull/313
> Don't create testset if no test to run

- CHANGELOG.md
- src/piracies.jl
Reflects current status of JuliaLang/julia#58131 PR to remove unnecessary work that is no longer viable.
> update piracies code to support v1.12 changes

- Project.toml
- test/test_smoke.jl
This dependency has already been removed in #221. It was added again in #224. However, it has not been removed when finally updating the required Julia version in #328.
This fixes an issue found after adding a Downgrade check to RootedTrees.jl in https://github.com/SciML/RootedTrees.jl/pull/192 and https://github.com/SciML/RootedTrees.jl/pull/194.
> remove unused dependency on Compat.jl
